version: '2'
# Persistent volume for the db
volumes:
  db_data:
services:
  darkstar-login:
    container_name: darkstar-login
    build: darkstar-login
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 0.0.0.0
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.4
    depends_on:
    - "darkstar-db"
  darkstar-search:
    container_name: darkstar-search
    build: darkstar-search
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.5
    depends_on:
    - "darkstar-db"
  darkstar-server-1:
    container_name: darkstar-server-1
    build: darkstar-server-1
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: darkstar-login
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.6
    depends_on:
    - "darkstar-db"
  darkstar-server-2:
    container_name: darkstar-server-2
    build: darkstar-server-2
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: darkstar-login
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.7
    depends_on:
    - "darkstar-db"
  darkstar-server-3:
    container_name: darkstar-server-3
    build: darkstar-server-3
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: darkstar-login
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.8
    depends_on:
    - "darkstar-db"
  darkstar-server-4:
    container_name: darkstar-server-4
    build: darkstar-server-4
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: darkstar-login
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.9
    depends_on:
    - "darkstar-db"
  darkstar-server-5:
    container_name: darkstar-server-5
    build: darkstar-server-5
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: darkstar-login
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.10
    depends_on:
    - "darkstar-db"
  darkstar-server-65:
    container_name: darkstar-server-6
    build: darkstar-server-6
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: darkstar-login
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.11
    depends_on:
    - "darkstar-db"
  darkstar-server-7:
    container_name: darkstar-server-7
    build: darkstar-server-7
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: darkstar-login
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.12
    depends_on:
    - "darkstar-db"
  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - "darkstar-db"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: darkstar-db
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.3
  darkstar-db:
     container_name: darkstar-db
     build: darkstar-db
     volumes:
     - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_LOGIN}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     networks:
      ffxi-docker:
        ipv4_address: 10.10.10.2

networks:
      ffxi-docker:
        driver: macvlan
        driver_opts:
          parent: enp5s0
        ipam:
          config:
          - subnet: 1darkstar-login/8
            gateway: 10.0.0.1
            ip_range: 10.10.10.0/24
