version: '2'
# Persistent volume for the db
volumes:
  db_data:
services:
  darkstar-lobby:
    container_name: darkstar-lobby
    build: darkstar-login
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.10
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.10
    depends_on:
    - "darkstar-db"

    darkstar-server-1:
    container_name: darkstar-server-1
    build: darkstar-server-1
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.10
      IP: 10.10.11.0
      PORT: 54230
    networks:
      ffxi-docker:
        ipv4_address: 10.10.11.0
    depends_on:
    - "darkstar-db"
    - "darkstar-login"
  
    darkstar-server-2:
    container_name: darkstar-server-2
    build: darkstar-server-1
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.10
      IP: 10.10.11.1
      PORT: 54231
    networks:
      ffxi-docker:
        ipv4_address: 10.10.11.1
    depends_on:
    - "darkstar-db"
    - "darkstar-login"

  darkstar-server-3:
    container_name: darkstar-server-3
    build: darkstar-server-1
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.10
      IP: 10.10.11.2
      PORT: 54232
    networks:
      ffxi-docker:
        ipv4_address: 10.10.11.2
    depends_on:
    - "darkstar-db"
    - "darkstar-login"

  darkstar-server-4:
    container_name: darkstar-server-4
    build: darkstar-server-1
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.10
      IP: 10.10.11.3
      PORT: 54233
    networks:
      ffxi-docker:
        ipv4_address: 10.10.11.3
    depends_on:
    - "darkstar-db"
    - "darkstar-login"

  darkstar-server-5:
    container_name: darkstar-server-5
    build: darkstar-server-1
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.10
      IP: 10.10.11.4
      PORT: 54234
    networks:
      ffxi-docker:
        ipv4_address: 10.10.11.4
    depends_on:
    - "darkstar-db"
    - "darkstar-login"

  darkstar-server-6:
    container_name: darkstar-server-6
    build: darkstar-server-1
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.10
      IP: 10.10.11.5
      PORT: 54235
    networks:
      ffxi-docker:
        ipv4_address: 10.10.11.5
    depends_on:
    - "darkstar-db"
    - "darkstar-login"

  darkstar-server-7:
    container_name: darkstar-server-7
    build: darkstar-server-1
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.10
      IP: 10.10.11.6
      PORT: 54236
    networks:
      ffxi-docker:
        ipv4_address: 10.10.11.6
    depends_on:
    - "darkstar-db"
    - "darkstar-login"

  #broker:
  #  container_name: broker
  #  build: pydarkstar
  #networks:
  #  ffxi-docker:
  #    ipv4_address: 10.10.10.4
  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - "darkstar-db"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: darkstar-db
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.3

  darkstar-db:
     container_name: darkstar-db
     build: darkstar-db
     volumes:
     - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_LOGIN}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       ZONE_IP: ${ZONE_IP}
     networks:
       ffxi-docker:
         ipv4_address: 10.10.10.2

networks:
      ffxi-docker:
        driver: bridge
        driver_opts:
          parent: enp5s0
        ipam:
          config:
          - subnet: 10.0.0.0/8
            gateway: 10.0.0.1
            ip_range: 10.10.10.0/23
