version: '2'
# Persistent volume for the db
volumes:
  db_data:
services:
  darkstar-login:
    container_name: darkstar-login
    build: darkstar-login
    links:
    - darkstar-db
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.4
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.4
    ports:
    - "54230:54230"
    - "54231:54231"
    - "54001:54001"
    - "54003:54003"
  darkstar-search:
    container_name: darkstar-search
    build: darkstar-search
    links:
    - darkstar-db
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.5
    ports:
    - "54002:54002"
  darkstar-server-1:
    container_name: darkstar-server-1
    build: darkstar-server-1
    links:
    - darkstar-db
    - darkstar-login
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.4
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.6
    ports:
    - "54230:54230/udp"
  darkstar-server-2:
    container_name: darkstar-server-2
    build: darkstar-server-2
    links:
    - darkstar-db
    - darkstar-login
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.4
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.7
    ports:
    - "54231:54230/udp"
  darkstar-server-3:
    container_name: darkstar-server-3
    build: darkstar-server-3
    links:
    - darkstar-db
    - darkstar-login
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.4
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.8
    ports:
    - "54232:54230/udp"
  darkstar-server-4:
    container_name: darkstar-server-4
    build: darkstar-server-4
    links:
    - darkstar-db
    - darkstar-login
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.4
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.9
    ports:
    - "54233:54230/udp"
  darkstar-server-5:
    container_name: darkstar-server-5
    build: darkstar-server-5
    links:
    - darkstar-db
    - darkstar-login
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.4
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.10
    ports:
    - "54234:54230/udp"
  darkstar-server-65:
    container_name: darkstar-server-6
    build: darkstar-server-6
    links:
    - darkstar-db
    - darkstar-login
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.4
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.11
    ports:
    - "54235:54230/udp"
  darkstar-server-7:
    container_name: darkstar-server-7
    build: darkstar-server-7
    links:
    - darkstar-db
    - darkstar-login
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
      MSG_SERVER: 10.10.10.4
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.12
    ports:
    - "54236:54230/udp"
  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
    - darkstar-db
    ports:
    - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: darkstar-db
    networks:
      ffxi-docker:
        ipv4_address: 10.10.10.3
  darkstar-db:
     container_name: darkstar-db
     build: darkstar-db
     ports:
     - "23055:3306"
     volumes:
     - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_LOGIN}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     networks:
      ffxi-docker:
        ipv4_address: 10.10.10.2

networks:
  ffxi-docker:
    ipam:
      driver: macvlan
      config:
        - subnet: 10.10.10.0/24