version: '2'
# Persistent volume for the db
volumes:
  db_data:
services:
  darkstar-server-all:
    container_name: darkstar-server-all
    build: darkstar-server-all
    links:
    - darkstar-db
    environment:
      MYSQL_HOST: darkstar-db
      MYSQL_LOGIN: ${MYSQL_LOGIN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVERNAME: ${SERVERNAME}
    ports:
    - "54230:54230"
    - "54230:54230/udp"
    - "54231:54231"
    - "54232:54231/udp"
    - "54232:54232/udp"
    - "54233:54233/udp"
    - "54234:54234/udp"
    - "54235:54235/udp"
    - "54236:54236/udp"
    - "54001:54001"
    - "54002:54002"
  darkstar-db:
     container_name: darkstar-db
     build: darkstar-db
     ports:
     - "23055:3306"
     volumes:
     - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_LOGIN}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
